### ISSUE TITLE
real-world illustration

### ISSUE THREAD

**Issue by corybrunson** [rrrlw/TDAstats#1]
The toy examples provided in with the package are helpful and wholly appropriate. The package would also benefit, i think, from an illustration using real-world data (as suggested but not required by the JOSS review checklist). Is there a dataset you've used for this purpose that could be included in the package and demonstrated either in the functional documentation or in a separate vignette? This isn't a sticking point for my review, but i do think the package would achieve its aims more effectively with such a case study.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/860)._

**Comment by rrrlw** [comment]
Yes, this is a great suggestion. Unfortunately, this package was created to cement the methodology of future research, rather than to solve a problem noticed in a prior project. As such, we do not yet have real-world data to which we have applied the functions in this package. I will leave the issue open, and when we do apply this method to real-world data with successful results, I will add the dataset and corresponding vignette/case study to the package.

**Comment by kaitai** [comment]
Hi -- I'm working on using this with real data and could contribute an illustration if I knew how to input a distance matrix to the TDAstats calculate_homology command. I know that Ripser is happy to work with distance matrices, but I don't see how to use a distance matrix with TDAstats, and so much real-world data requires a distance matrix (financial data, health data, etc.). 

Let me know how to input a distance matrix and I'll give you a nice real-world application!

**Comment by ShotaOchi** [comment]
Does the following code work?
```
calculate_homology(mat, format = "distmat")
```

**Comment by kaitai** [comment]
Thanks for the reply.

`calculate_homology(mat, format = "distmat")`
does work as long as mat is 

- a symmetric (distance) matrix, or
- a lower-triangular matrix with zeros elsewhere. 

It does not work if mat is upper-triangular or the output of R's `dist` function, for what it's worth -- but dist does have a funky output format.

I'll try to submit a real-world example by next Tuesday.

**Comment by rrrlw** [comment]
Great, looking forward to seeing the real-world example @kaitai. Happy that TDAstats was helpful. And thank you, @ShotaOchi, appreciate the helpful answer.

**Comment by kaitai** [comment]
I should have been wiser than to promise anything during the first week of the semester. I put an Rmd file on my github page and am happy to contribute it.
[https://github.com/kaitai/Example-with-TDAstats](url)

**Comment by rrrlw** [comment]
No worries, all contributions are appreciated. The link you included does not seem to be working for me; does it point to a private repo?

**Comment by rrrlw** [comment]
Looks wonderful, thank you! I will link it to the TDAstats main page soon.

**Comment by rrrlw** [comment]
The link has been added to the Applications section of the README. Thank you, @kaitai!
