### ISSUE TITLE
limit of the filtration

### ISSUE THREAD

**Issue by mlnjsh** [rrrlw/TDAstats#12]
How Do i set limit for filtration value? say for example i want to grow my simplicies upto radius 5

**Comment by ShotaOchi** [comment]
set threshold to 5
<pre>
calculate_homology(mat, <b>threshold=5</b>)
</pre>

**Comment by ShotaOchi** [comment]
Oops! threshold should be set to 10 instead of 5, 
because threshold is maximum diameter.
