### ISSUE TITLE
Support for other field coefficients  

### ISSUE THREAD

**Issue by peekxc** [rrrlw/TDAstats#14]
This is more of a question. 

Is it in the scope of this package to re-adjust the ripser source code to support other coefficients in a prime field?

As you know, this should simply involve replacing areas like e.g. [here](https://github.com/rrrlw/TDAstats/blob/0700bfff999f0c54e33994111b19a602116d6a6b/src/ripser_short.cpp#L100-L104) with the code compiled when the __USE\_COEFFICIENTS__ preprocessor variable is enabled in the ripser package. 

I imagine usage like
```R
TDAstats::calculate_homology(unif2d, dim=1, p=11)
```
or something

**Comment by rrrlw** [comment]
Yes, particularly given that it's a Ripser feature, this would definitely be within the scope of the package. Unfortunately, I won't be able to get to adding it for a while - is this something you would be willing to add to TDAstats?

**Comment by peekxc** [comment]
Seeing how I'll need it soon, yes I'll fork and PR soon-ish

**Comment by rrrlw** [comment]
Sounds good, thank you!

**Comment by peekxc** [comment]
See PR #15 for code changes

**Comment by rrrlw** [comment]
Sorry I have been slow to respond, it looks like PR #15 has been closed for further editing. Let me know when it's ready or if there's anything with which I can help!

**Comment by rrrlw** [comment]
solved by #19, thank you @peekxc 

code from #19 ported to `rrrlw/ripserr` (will add this as a TDAstats dependency after CRAN acceptance)
